### ISSUE TITLE
apex Type Not found

### ISSUE THREAD

**Issue by maryembourhi** [financialforcedev/apex-mdapi#106]
I'am trying to access the information about an object, i keep getting the following exception:
<b>Web service callout failed: Unable to parse callout response. Apex type not found for element restrictedPicklist</b>

I have no idea what i am missing in the mdapi class .

**Comment by afawcett** [comment]
This wrapper is generated from the official Salesforce Metadata API WSDL (Web Service Definition Language) file downloaded from the service for a given release. This means that responses should only contain elements described in that WSDL and thus the wrapper should be able to parse all possible responses. However..... it seems you've managed to get the platform to generate a response that contains an element not originally described in the WSDL i used to generate the library last. This actually is not the first time. We can work around this by hand modifying the wrapper code for now. Can you provide some more details and sample code (just the bit making the call and some inputs) please?

**Comment by MichaelMi** [comment]
i try to use metadata service to retrieve contract metadata, throw an exception "System.CalloutException: Web service callout failed: Unable to parse callout response. Apex type not found for element restrictedPicklist"

i try to add the missing element to metadataservice class, but i can not know where was i add to it .

can you help me to resolve this problem

**Comment by afawcett** [comment]
Sure, my advice is still as per my last response, did you take a look at that? It seems like you have stumbled accrosss a pilot feature, http://salesforce.stackexchange.com/questions/9322/what-does-a-restricted-picklist-mean. Have you had this enabled in your org? I suspect because its pilot, it does not appear in the WSDL used to generate the Apex Metadata API wrapper stored in this repo. You can either have the pilot disabled, or teach your copy of the Apex Metadata API about the new field as i suggested above.

**Comment by afawcett** [comment]
@MichaelMi i'll close this issue now, ping me back here if you still want to work this issue.
