### ISSUE TITLE
AssignmentRules issue for Case

### ISSUE THREAD

**Issue by sathishvenks** [financialforcedev/apex-mdapi#130]
This is the readMetadata request and response XMLs got from the code.

Request:

`<readMetadata xmlns="http://soap.sforce.com/2006/04/metadata">
			<type>AssignmentRules</type>
			<fullNames>Case</fullNames>
		</readMetadata>`

Response(truncated):

`<records xsi:type="AssignmentRules">
               <fullName>Case</fullName>
               <assignmentRule>
                  <fullName>Standard</fullName>
`

But when I just amended the criteria and update the metadata, I received Unknown Exception error. Below is the sample UpdateMetadata request and response

Request:
`<metadata xsi:type="AssignmentRules">
				<fullName>Case</fullName>
				<assignmentRule xsi:type="AssignmentRule">
					<fullName>Standard</fullName>`

Response:
`<result>
            <errors>
               <message>unexpected metadata</message>
               <statusCode>UNKNOWN_EXCEPTION</statusCode>
            </errors>
            <fullName>Case</fullName>
            <success>false</success>
         </result>
`
Apex example attached
[ApexEx.txt](https://github.com/financialforcedev/apex-mdapi/files/253769/ApexEx.txt)

**Comment by afawcett** [comment]
This is a [GACK](https://developer.salesforce.com/blogs/engineering/2015/02/gack.html) by the looks of it, a Salesforce internal error, it should have some kind of numbers associated with it though? Since you have the XML request sample this is ideal for passing to Salesforce Support (passing Apex MD code will raise to many unneccessary questions as to how your calling the API). My recommendation is to raise a case and given them a way to reproduce this via something like Developer Workbench or CURL with your sample XML and of course support org login granted. Another option to try retrieving one you created in the UI and pull that down, maybe its missing some fields and there is a platform bug in the error handling? Experiment with different assignment rule setups as well. Ultimatly the time you spend on this can server to have Salesforce support help you more quickly, of course you could go both routes and get a case underway. Hope this helps! 👍
