### ISSUE TITLE
Invalid Session Id

### ISSUE THREAD

**Issue by ayesha-warraich** [financialforcedev/apex-mdapi#153]
Hi!

I am trying to call the metadata service from my lightning component. My component calls the java script method which in turn calls the Aura Enabled Apex Method in the controller. In the Apex Method

      MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        system.debug(UserInfo.getSessionId());

MetadataService.RecordType recordType = (MetadataService.RecordType) service.readMetadata(
   'RecordType', new String[] { 'Case.Customer' }
).getRecords()[0];

I am trying to get the picklist values from this record type to show in my lightning component. I am able to run this when I execute it from the Execute Anonymous window. Any help on this would be greatly appreciated!

This is the error i get -
 FATAL_ERROR System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

**Comment by afawcett** [comment]
This is a known issue in Lightning, take a look at [this](http://salesforce.stackexchange.com/questions/110515/getting-session-id-in-lightning#111396) for a workaround. I am not however advocating the workaround. It is intentional that Salesforce have reduce the capability of the Lightning context Session Id, for security reasons. Not that for compatibility reasons Visualforce context running Lightning still works. So it might be safer and not require a hack to implement your functionality in Visualforce. Anyway, up to you, just some thoughts. Hope this helps! 👍  Also keep in mind users using your component will need "API Access" on their profile/permission set regardless. Are you sure Apex will not give you what you want? https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_Schema_RecordTypeInfo.htm
