### ISSUE TITLE
Need help in connecting MetadataAPI using Named credentials

### ISSUE THREAD

**Issue by B--Force** [financialforcedev/apex-mdapi#169]
Im facing challenge in retrieving the accesstoken from named credentials which is required for retrieving metadata using Apexwrapper MetadataAPI Please help me with any suggestions.

For Ex.

public static MetadataService.MetadataPort createService(String **Accesstoken**)
    {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = **Accesstoken**;
        return service;
    }
Thanks in Advance

**Comment by afawcett** [comment]
There is quite a bit required to use Named Credntials with Salesforce API's last i looked. You can read more [here](http://www.jitendrazaa.com/blog/salesforce/salesforce-to-salesforce-integration-using-named-credentials-in-just-5-lines-of-code/) and [here](http://www.jitendrazaa.com/blog/salesforce/login-to-salesforce-from-salesforce-using-authentication-provider/#more-4516). It is something i have been meaning to look into further but not yet had the time. There was also another poster that said they would look into it [here](https://github.com/financialforcedev/apex-mdapi/issues/89). I have pinged them on that issue to see if they ever got it working. Hope this helps for now! Good luck! 👍

**Comment by gspei** [comment]
We have managed to get it working, but there's an issue with the way the Metadata API behaves that causes the token refresh process to not occur properly.

In a nutshell, everything works fine after setup, but after a period of time (when your session expires), you get an error similar to:
Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session hash: xxxxx This error usually occurs after a session expires or a user logs out. faultcode=sf:INVALID_SESSION_ID faultactor=

The root cause is that the Metadata API is returning a 500 when the session expires, not a 401, so the Named Credentials infrastructure doesn't know to try to do a token refresh.

We discovered that a workaround is to first make a call to one of the REST APIs (e.g. /limits) to cause the access token to be refreshed, then proceed with the Metadata API call afterwards.

After some robust discussions with Salesforce and the product management team, they have published https://help.salesforce.com/apex/HTViewSolution?urlname=Named-credential-oauth-token-doesn-t-get-automatically-refreshed-with-Salesforce-SOAP-API-end-point&language=en_US

**Comment by afawcett** [comment]
Ha @gspei thanks for sharing, i recall seeing that article a few days ago. Thanks for driving out this issue with Salesforce. Using Named Credentials is quite a common ask here, would be happy to share some steps on how to do it? I would be happy to post on the wiki here or you are more than welcome to guest blog on my blog if you wish (or use your own of course). Let me know and thanks again! 👍

**Comment by gspei** [comment]
@afawcett Awesome - I'm planning to write a blog post on this at some point - I'll share the link here once it's available.

**Comment by afawcett** [comment]
@gspei this will for sure be very popular i know it! 👍

**Comment by gspei** [comment]
@afawcett I have published a blog post here https://goo.gl/7F81Fk with step by step details on how to use Named Credentials with apex-mdapi.

**Comment by afawcett** [comment]
Amazing thanks! 👍

**Comment by juandomenechh** [comment]
> @afawcett I have published a blog post here https://goo.gl/7F81Fk with step by step instructions on how to use Named Credentials with apex-mdapi.

@ab0369  Post seems to be brought down. Have you, by any chance, saved that information anywhere else?
Thank you very much in advance :)

**Comment by gspei** [comment]
@juandomenechh  Here's the new link https://gscloudsolutions.com/tips-tricks/using-named-credentials-with-the-apex-wrapper-salesforce-metadata-api/

**Comment by juandomenechh** [comment]
Amazing, thanks @gspei!

**Comment by CarterAKornfeld** [comment]
Hey, I am still struggling to solve the API problem involving the session ID and a result get the following error: 
Line: 13532, Column: 1System.CalloutException: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=


Can anyone explain a solution to the problem, I can give addition information as needed. Thanks.
