### ISSUE TITLE
MetadataService.CustomField is always NULL and all Read Metadata Code returns NULL

### ISSUE THREAD

**Issue by codewerk** [financialforcedev/apex-mdapi#183]
CustomField is NULL.
Can anyone suggest a resolution for this common code snippet below? The field exists and I can create/update using the Apex Metadata API just fine.

Code run in anonymous apex window
--------------------------------------
```java
MetadataService.MetadataPort service = new MetadataService.MetadataPort();
service.SessionHeader = new MetadataService.SessionHeader_element();
service.SessionHeader.sessionId = UserInfo.getSessionId();
// Read Custom Field
MetadataService.CustomField customField = (MetadataService.CustomField) service.readMetadata(
    'CustomField', new String[] { 'Account.CustomerPriority__c' }
).getRecords()[0];

System.debug( 'custom field = ' + customField ); //Null error here.
```

Debug log lines
----------------
23:09:57:064 USER_DEBUG [9]|DEBUG|custom field = CustomField:[Metadata.fullName=null, apex_schema_type_info=(http://soap.sforce.com/2006/04/metadata, true, false), caseSensitive=null, caseSensitive_type_info=(caseSensitive, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), customDataType=null, customDataType_type_info=(customDataType, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), defaultValue=null, defaultValue_type_info=(defaultValue, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), deleteConstraint=null, deleteConstraint_type_info=(deleteConstraint, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), deprecated=null, deprecated_type_info=(deprecated, http://soap.sforce.com/2006/04/metadata, null, 0, 1, false), description=null, 
....

**Comment by BoonPlus** [comment]
Have you tried MetadataService.FileProperties? Try the code below and let us know.

service.SessionHeader.sessionId = UserInfo.getSessionId();
List<MetadataService.ListMetadataQuery> queries = new List<MetadataService.ListMetadataQuery>();        
MetadataService.ListMetadataQuery queryApplication = new MetadataService.ListMetadataQuery();
queryApplication.type_x = 'CustomField';
queries.add(queryApplication);                                   
MetadataService.FileProperties[] fileProperties = service.listMetadata(queries, 39);
for (MetadataService.FileProperties fileProperty : fileProperties) 
    if (fileProperty.fullName.contains('CustomerPriority__c')) { system.debug('fileProperty = ' + fileProperty); break; }

**Comment by codewerk** [comment]
Appreciate the prompt response. I tried the code snippet which returned some info, but I was trying to obtain the 'controllingfieldvalues' for each picklist value. Then, after adding a new pl value, which destroys existing dependencies & inactivates recordtype assignments, I can add them back in an update.

**Comment by afawcett** [comment]
I have confirmed with Salesforce. You cannot retrieve just CustomFIeld's on their own, you have to retrieve the parent CustomObject.

**Comment by ajazm** [comment]
Thanks for confirming. I have been following your posts and APIs since a business requirement popped in.

The requirement was to create a recordType dynamically and create a picklist value in the same Object's custom picklist field.

I am able to create a recordType after referring to the metadataAPI class that you have briliantly compiled. But while creating picklist value in a custom field I was getting null exception. I landed on this page.

As per the suggestion, while I was retrieving the customObject, I am getting below error.

EXCEPTION_THROWN|[11578]|System.CalloutException: IO Exception: Read timed out
FATAL_ERROR|System.CalloutException: IO Exception: Read timed out

The code is plain and simple.

`MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = sessionId;
        
        MetadataService.CustomObject customObject =
            (MetadataService.CustomObject) service.readMetadata('CustomObject',
                new String[] { 'Products_Services__c' }).getRecords()[0];
        for(MetadataService.CustomField field : customObject.fields)
            System.debug(field.fullName);`

Can you help me identify where I am wrong ? I am guessing this might be because, the custom object has over 700 custom fields, this is causing the timeout problem. Can you help me if this is the case how can I make an entry in picklist field ?
