### ISSUE TITLE
Transition of repo to native Apex Metadata API

### ISSUE THREAD

**Issue by up2go-rsoesemann** [financialforcedev/apex-mdapi#190]
[As described here Salesforce will provide more and more Metadata access via Apex](https://developer.salesforce.com/blogs/engineering/2017/05/introducing-apex-metadata-api.html) so that a a certain time will be no need anymore for this repos code.

In the years during transition what is the roadmap for this repo. Will the code be rewritten to just wrap the new Apex functionality? What is the recommended strategy for users of this repo?

**Comment by dfruddffdc** [comment]
Definitely want @afawcett 's two pennies on this.

Personally, I look forward to the day this library becomes obsolete! 😃 

I think users should opt for the native metadata API whenever possible, but fall back to this library when it isn't. I don't know if there ever will be complete functional parity - e.g. will Salesforce endorse packages with the ability to delete metadata in subscriber orgs?

The classes in the Metadata namespace seem to mostly be a counterpart to those in this library. I've converted code over to the native API, which was simply a case of:
* Switching the MetadataService class for the Metadata namespace
* Using Enums instead of Strings
* Switching to the native read/write methods
I couldn't see anywhere we could add value by wrapping up the native Apex Metadata API. But I'm certainly interested in your take on it!

**Comment by afawcett** [comment]
Yep agree with @dfruddffdc, more than happy to see it become obsolete. Where there is support for what you need the native API design was deliberately designed to mirror this one sto make the migration described above possible. 👍 

**FYI:** A couple of new wrappers have emerged around the new Apex API
- [Managing layouts](https://github.com/financialforcedev/df17-mdapi)
- [Managing custom metadata](https://github.com/afawcett/custommetadataapi)
