### ISSUE TITLE
With API v38.0, what could be the risks if we set the apiVersion to the latest version?

### ISSUE THREAD

**Issue by BoonPlus** [financialforcedev/apex-mdapi#205]
Instead of updating the library for the latest API (i.e. to avoid the maximum size of an allowed Apex class), what could be the risks if we set the apiVersion to the latest version in our codes? Will we gain anything if we do this?
e.g.
public Double apiVersion = 42

**Comment by dfruddffdc** [comment]
I think you're saying your codebase is generally using API v38.0. You are considering modifying this library to use v38.0 also.

Modifying the class API versions in the cls-meta.xml files is probably fine, but you may need to make a few tweaks to comply with the earlier API version.

Modifying the API version of the Metadata API callout made by `MetadataService.MetadataPort` is possible, but not advisable. Obviously, the API is versioned for backwards compatibility, and Salesforce will respect Metadata supplied in the format expected as of [v38.0](https://github.com/financialforcedev/apex-mdapi/blob/7fd563326659eeb8f00abd83990cb0d859b5fd7f/apex-mdapi/src/classes/MetadataService.cls).

Should I change MetadataService so it has `apiVersion = 38`?
* You can, but I can't see any advantage to doing so.

Well, why shouldn't I change MetadataService so it has `apiVersion = 38`?
* You can't use newer features
    * With each release, [new Metadata types](https://releasenotes.docs.salesforce.com/en-us/spring18/release-notes/rn_api_meta.htm?edition=&impact=) are added.
    * For example, you can't read/write the CustomField metadataRelationship​ControllingField field, which was introduced in Spring 17 - you have to review which features become unavailable and decide how much of a problem that is.
* Salesforce could stop supporting v38.0.
    * Not any time soon. However, I would feel very uncomfortable continuing to use v38.0 by the time API v48.0 is released.
* When you want to upgrade, you will find it more challenging to make bigger jumps in API version
    * For example. it's harder to go from v38.0 to v48.0 than from v47.0 to v48.0.
    * We try to keep our code (and the APIs we use) at or just below the current API version, and certainly no more than 3 releases behind.
* You diverge from the main codepath in this repo.
    * You will not be able to take advantage of enhancements or bug fixes in this repo, without implementing them manually in your divergent codebase.

Ok, should I keep my classes on v38, and MetadataService on `apiVersion = 42`? What happens when 43 is released? Or 44? etc. etc.
* Upgrading aggressively with each new Salesforce release is costly. There are advantages to "doing little, often" over "doing large, rarely" - but you have to find that balance.

That's my two cents, happy to discuss further - but closing the issue in the meantime as it doesn't represent any required work on the library.

**Comment by BoonPlus** [comment]
@dfruddffdc thanks for the feedback. I generated V42.0 MetatdataService.cls and MetataSercviceTest.cls and them to the code branch.

**Comment by afawcett** [comment]
I'll get a PR done for the latest version! There is a few more complications to consider with the latest version, but it looks like there is a good solution. https://github.com/financialforcedev/apex-mdapi/issues/186
